### ISSUE TITLE
How to resample full color image?

### ISSUE THREAD

**Issue by shenck0** [komrad36/CUDALERP#1]
This code works fine on grayscale image. Thanks for sharing.
And how to modify code to support reampling color image. e.g. the image is composed of RGB channels in 32bit float type.

**Comment by komrad36** [comment]
I can make you a color version! First I need to clarify, though; do you mean that each pixel is composed of 3 floats? That's 12 bytes per pixel. That's a lot! Usually RGB tends to be 8 bit unsigned integers per color, for a total of 24 bits, or maybe RGBA for a total of 32 bits. What do you need?

Also, a star or watch would be much appreciated if you find my work useful!

-Kareem

**Comment by shenck0** [comment]
I need to resize RGB image to produce input data for neural network, so every pixel is composed of three 32bit float numbers. 
For example, a 2x2 image:
     RED    GREEN
     BLUE   BLACK
the input array should be : new float[3*4] { 255,0,0,0,  0,255,0,0,  0,0,255,0 }
Any clue would be appreciated!

In addition, I have tried function nppiResizeSqrPixel_32f_P3R in NPP(NVIDIA Performance Primitives) library, but it produces low quality images when upsampling small images.

**Comment by komrad36** [comment]
I see. Okay I can make something like that! Give me about a day or so.

From that example input it looks like the input format is RRRRGGGGBBBB. Shouldn't it be RGBRGBRGBRGB? i.e. for your example, stored row-major, it'd be

```
{255, 0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0};
{ R , G, B, R,  G , B, R, G,  B , R, G, B};
{    red,      green,     blue,    black  };
```
?

**Comment by shenck0** [comment]
The input format is RRRRGGGGBBBB in my case. (Image is described as a Channel x Height x Width array, stored in row-major order)
I think a float-version CUDANERP()/CUDALERP() would make things easier for me, and then I can resize the whole image channel by channel.

**Comment by komrad36** [comment]
I see! Yes, in that case a simple single-float version will work just fine, and you can just tell CUDALERP that your image consisting of `n` pixels is actually 3 different images, and it will work. Cool, I'll work on that after I get some sleep.

**Comment by komrad36** [comment]
Alright, new project, [CUDAFLERP](https://github.com/komrad36/CUDAFLERP), is up! I decided to keep them separate since they ended up differing quite a bit in the CUDA texture setup. Let me know if it does what you want or if there are any problems, since I haven't had a chance to test it as thoroughly as the uint8_t version. Hope it helps! :)

**Comment by komrad36** [comment]
You can see what changes were made to adapt CUDALERP into CUDAFLERP - the core remains the same but we no longer sample normalized floats from tex. Now we just get the float elements directly. Therefore we no longer scale back to 255.0f, and we no longer add 0.5f to the final answer because no truncation is happening. A few other minor changes in the setup logic, like we now move 4 times more bytes, but that's the basics! Let me know if any other questions about what I did to adapt it.

Also note that for speed I'm using `float `scale factors; if you use a truly ridiculous scale like x10,000, this will produce incorrect pixels occasionally. This is known and is avoidable if you use `double `instead, but it's not worth it. You lose a lot of speed for a use case that should never be required. If you use reasonable scales, i.e. less than about x1000, CUDALERP and CUDAFLERP produce pixel-exact results.

**Comment by shenck0** [comment]
Sorry for late reply. I have added CUDAFLERP to my code, and it works well!
I really appreciate your help!
